import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const source = (file: string) => readFileSync(require('node:path').resolve(__dirname, file), 'utf8')
describe('bright tarot entry wiring', () => {
  it('keeps the existing flow behind a light home and returns home on close', () => {
    const page = source('./index.tsx')
    expect(page).toContain('tarot-panel-v2.jpg')
    expect(page).toContain('tarot-card-single-v3.png')
    expect(page).toContain('tarot-cards-fan-v3.png')
    expect(page).toContain('快速获得指引')
    expect(page).toContain('深度探索指引')
    expect(page).toContain("startFlow('single')")
    expect(page).toContain("startFlow('triple')")
    expect(page).toContain('flowOpen ?')
    expect(page).toContain('onClose={closeFlow}')
    expect(page).toContain('initialSpread={spread}')
  })
  it('renders skin thumbnails as fit-inside over blurred fill backdrop', () => {
    const page = source('./index.tsx')
    expect(page).toContain('tarot-home__skin-thumb-bg')
    expect(page).toContain('tarot-home__skin-thumb-fg')
    expect(page).toContain('mode="aspectFill"')
    expect(page).toContain('mode="aspectFit"')
    const styles = source('./index.scss')
    expect(styles).toContain('.tarot-home__skin-thumb-bg')
    expect(styles).toContain('.tarot-home__skin-thumb-fg')
  })
  it('curtain entrance layers star twinkle, seam glow, moon fade and flow reveal', () => {
    const page = source('./index.tsx')
    expect(page).toContain('tarot-curtain__glow')
    expect(page).toContain('tarot-curtain__star--a')
    expect(page).toContain("curtain === 'opening' ? 'tarot-page--reveal' : ''")
    const styles = source('./index.scss')
    expect(styles).toContain('@keyframes tarot-flow-reveal')
    expect(styles).toContain('@keyframes tarot-star-twinkle')
    expect(styles).toContain('.tarot-curtain--opening .tarot-curtain__dream')
    expect(styles).toContain('.tarot-curtain--holding .tarot-curtain__glow')
  })
  it('listens for history at the always-mounted page, including repeat requests', () => {
    expect(source('./index.tsx')).toContain('Taro.eventCenter.on(TAROT_HISTORY_OPEN_EVENT, openHistory)')
    expect(source('./index.tsx')).toContain('historyRequest={historyRequest}')
    expect(source('../../features/tarot/MiniappTarotFlow.tsx')).toContain('if (historyRequest > 0) setHistoryOpen(true)')
  })
})
